# Generated by Django 4.0.4 on 2023-06-27 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('long_URL', models.CharField(max_length=2050)),
                ('short_URL', models.CharField(editable=False, max_length=7, unique=True)),
            ],
        ),
    ]
