# Generated by Django 4.0.4 on 2023-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_count_alter_form_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
