# Generated by Django 4.0.4 on 2023-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_count_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
