# Generated by Django 4.0.4 on 2023-06-27 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_form_short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('original_url', models.URLField(max_length=2050)),
                ('short_url', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('time_date_created', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
