# Generated by Django 4.0.4 on 2023-07-01 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_shorturl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='user',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
