# Generated by Django 4.0.4 on 2023-07-01 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_remove_shorturl_user_shorturl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
